# -*- coding: utf-8 -*-
"""ToyProject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iV_QKTN07EaXoHO3CKim-hzUGIJYVDAR
"""

import pandas as pd

df = pd.read_csv('/content/Study Hour(Linear Regression) 2.csv')

df

import numpy as np

df.shape

df.info()

import matplotlib.pyplot as plt

plt.scatter(df['Hours'],df['Scores'])

X = df.iloc[:,0:2]



X



Y = df.iloc[:,-1]

Y

